### ISSUE TITLE
About yii2 PR 14701

### ISSUE THREAD

**Issue by bscheshirwork** [rob006/yii2-simple-auth#5]
I think 
after merge this PR 
https://github.com/yiisoft/yii2/pull/14701
we need use
"psr/http-message": "~1.0.0",
too?
> In particular: method `getHeaders()` and corresponding virtual property `$headers` are no longer return `HeaderCollection`

i.e. change 
https://github.com/rob006/yii2-simple-auth/blob/ed5e107df095c3f3987e69d2e01dac2c86dbce43/src/ActionFilter.php#L100-L104

like
```
if (!Yii::$app->getRequest()->getHeaderLine($this->headerName)) { 
    return false; 
} 
$token = Yii::$app->getRequest()->getHeaderLine($this->headerName); 
```
or
```
if (!Yii::$app->getRequest()->hasHeader($this->headerName)) { 
    return false; 
} 
$token = Yii::$app->getRequest()->getHeader($this->headerName); 
```

?

**Comment by rob006** [comment]
You're right, but this extension does not yet support Yii 2.1 (which is not even released). 
There are also other PRs/ideas which may affect this extension, e.g. #14645.

I have to wait until Yii 2.1 will be released, there is no point to try to fix this earlier.

**Comment by rob006** [comment]
Yii 2.1 will not be released.
